### PR TITLE
Adding missing decorator

### PR DESCRIPTION
**Pull request by sriprasanna**

### CODE REVIEW

**Comment by andrewvc** [comment]
LGTM

**Comment by andrewvc** [comment]
Will release shortly, thanks @sriprasanna !

**Comment by andrewvc** [comment]
@sriprasanna before we can accept this patch can you sign the CLA? https://www.elastic.co/contributor-agreement it just takes a second!

Also, I'd appreciate it if you could bump the version to 1.0.2 in the gemspec and add an entry to the changelog. Thanks!

**Comment by sriprasanna** [comment]
@andrewvc Done. Let me know if anything else to be added.

**Comment by andrewvc** [comment]
Thanks @sriprasanna , I'm about to release the new version :)

**Pull request closed without merging**
