### PR TITLE
No retries by default

### PR DESCRIPTION
**Pull request by andrewvc**
By default manticore retries all requests 3 times. This is unexpected behavior for this application, very bad when using it to health check URLs for instance. Let's make 0 retries the default from now on, it's still overridable however.

### CODE REVIEW

**Comment by suyograo** [comment]
+1 on not retrying by default. Do we log an error when URL cannot be accessed?

**Comment by andrewvc** [comment]
@suyograo we actually send a special error message with all the request metadata in the event of an error.

**Comment by andrewvc** [comment]
@suyograo I mean a special error event

**Comment by suyograo** [comment]
@andrewvc ok. LGTM

**Pull request closed without merging**
